#!/usr/bin/env bash

# Parallel version of the compile and test script

set -e

nValue="20"
numberOfThreads="4"

# Loads mpi-module if on CIMS
if [[ "$(uname -s)" == "Linux" ]]; then
	module load openmpi-x86_64
fi

# Compiles
if [[ "$(uname -s)" == "Darwin" ]]; then
	clang-omp -fopenmp -g -Wall -o genprime genprime.c
else
	gcc -fopenmp -g -Wall -o genprime genprime.c
fi

# Executes and generates the output file
./genprime $nValue $numberOfThreads

# Diffs the parallel version
diff $nValue.txt testing/answer/$nValue.txt
